import { MacroScorecard } from "./macro-scorecard";
import { displayFacts } from "@/lib/ai/display-facts";
import type { SavedGoldAnalysis } from "@/lib/data/gold-analyses";
import { cn } from "@/lib/utils";
import { EconomicCalendarSection, FinanceCalendarAttribution } from "./economic-calendar";

const panel = "rounded-[10px] border border-line bg-surface p-5";
const title = "text-[11px] font-semibold uppercase tracking-[.14em] text-muted";
export const biasLabel = (value: string) => value.replaceAll("_", " ");
export function AnalysisReport({ report }: { report: SavedGoldAnalysis }) {
  const analysis = report.analysis; const snapshot = report.dataSnapshot;
  const facts = displayFacts(snapshot);
  return <div className="space-y-5">
    <div className="grid gap-5 lg:grid-cols-2"><section className={panel}><h2 className={title}>Fundamental bias · AI interpretation</h2><p className={cn("mt-4 text-xl font-semibold uppercase tracking-tight", analysis.bias.includes("bullish") ? "text-profit" : analysis.bias.includes("bearish") ? "text-loss" : "text-foreground")}>{biasLabel(analysis.bias)}</p><div className="mt-5 flex items-baseline gap-3"><span className="text-xs text-muted">Confidence</span><span className="text-2xl font-semibold tabular-nums">{analysis.confidence}<span className="text-sm font-normal text-muted"> / 100</span></span></div><p className="mt-3 text-xs leading-5 text-muted">Confidence reflects evidence, conflicting signals, and data coverage.</p></section><section className={panel}><h2 className={title}>Scenario outlook</h2><div className="mt-4 space-y-3">{(["bearish", "range", "bullish"] as const).map(key => <div key={key}><div className="flex justify-between text-sm"><span className="capitalize text-secondary">{key}</span><span className="font-semibold tabular-nums">{analysis.probabilities[key]}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded bg-foreground/5"><div className={cn("h-full rounded", key === "bullish" ? "bg-profit/60" : key === "bearish" ? "bg-loss/60" : "bg-accent/60")} style={{ width: `${analysis.probabilities[key]}%` }} /></div></div>)}</div><p className="mt-4 text-xs leading-5 text-muted">Scenario confidence estimates based on available evidence. These are not calibrated market probabilities.</p></section></div>
    <EconomicCalendarSection calendar={snapshot.economicCalendar} />
    <section className={panel}><h2 className={title}>Why this bias?</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-secondary">{analysis.summary}</p>{snapshot.economicCalendar && <FinanceCalendarAttribution />}</section>
    <section className={panel}><h2 className={title}>Key drivers</h2><ol className="mt-4 grid gap-4 sm:grid-cols-2">{analysis.keyDrivers.map((driver, index) => <li key={index} className="flex gap-3 text-sm leading-6 text-secondary"><span className="font-mono text-accent">{String(index + 1).padStart(2, "0")}</span>{driver}</li>)}</ol></section>
    <div className="grid gap-5 lg:grid-cols-3">{(["bearish", "range", "bullish"] as const).map(key => {
      const scenario = key === "bullish" ? analysis.bullishScenario : key === "bearish" ? analysis.bearishScenario : analysis.rangeScenario;
      const invalidation = key === "bullish" ? analysis.bullishScenario.invalidation : key === "bearish" ? analysis.bearishScenario.invalidation : null;
      return <section key={key} className={panel}><div className="flex items-center justify-between gap-2"><h2 className={title}>{key} scenario</h2><span className="text-sm font-semibold tabular-nums">{scenario.probability}%</span></div><p className="mt-4 text-sm leading-6 text-secondary">{scenario.explanation}</p><p className="mt-4 text-xs font-semibold text-foreground">Conditions</p><Lines items={scenario.conditions} />{invalidation && <><p className="mt-4 text-xs font-semibold text-foreground">Invalidation</p><Lines items={invalidation} /></>}</section>;
    })}</div>
    <section className={panel}><h2 className={title}>What would change the bias?</h2><Lines items={analysis.whatWouldChangeBias} /></section>
    <MacroScorecard key={report.id} snapshot={snapshot} rows={analysis.macroScorecard} />
    <div className="grid gap-5 lg:grid-cols-2"><section className={panel}><h2 className={title}>Recent macro context</h2>{analysis.recentMacroDevelopments.length ? <Lines items={analysis.recentMacroDevelopments} /> : <p className="mt-4 text-sm text-muted">No recent developments supported by the supplied data.</p>}<p className="mt-4 text-xs text-muted">{snapshot.economicCalendar ? "Calendar and consensus coverage are shown above; null estimates remain unavailable." : "Consensus and calendar data unavailable in this saved snapshot."}</p></section><section className={panel}><h2 className={title}>Risks</h2><Lines items={analysis.risks} /></section></div>
    <section className={panel}><h2 className={title}>Data quality · Backend assessment</h2><p className="mt-4 text-lg font-semibold">{snapshot.dataQuality.completeness}% <span className="text-xs font-normal text-muted">completeness</span></p>{snapshot.dataQuality.categories && <div className="mt-4 grid gap-3 sm:grid-cols-2">{snapshot.dataQuality.categories.map(category => <div key={category.name} className="rounded border border-line p-3 text-xs"><div className="flex flex-wrap justify-between gap-2"><span className="font-medium text-secondary">{category.name}</span><span className="text-accent">{category.status}</span></div><p className="mt-2 leading-5 text-muted">{category.detail}</p></div>)}</div>}{snapshot.economicCalendar && <FinanceCalendarAttribution />}<div className="mt-4 grid gap-4 sm:grid-cols-2"><div><p className="text-xs font-semibold">Missing</p><Lines items={snapshot.dataQuality.missingData} /></div><div><p className="text-xs font-semibold">Unexpectedly stale</p>{snapshot.dataQuality.staleData.length ? <Lines items={snapshot.dataQuality.staleData} /> : <p className="mt-2 text-xs text-muted">None</p>}</div></div><details className="mt-5 border-t border-line pt-4"><summary className="cursor-pointer text-xs font-semibold text-muted">Warnings and coverage</summary><Lines items={snapshot.dataQuality.warnings} /></details><details className="mt-4"><summary className="cursor-pointer text-xs font-semibold text-muted">All source facts ({facts.length})</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{facts.map(fact => <div key={fact.key} className="rounded border border-line p-3 text-xs leading-5"><a href={fact.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-accent">{fact.name}</a><p>{fact.value} · {fact.change}</p><p className="text-muted">Observation {fact.date ?? "unavailable"} · {fact.source}</p><p className="text-muted">Fetched {fact.fetchedAt}</p><p className="text-muted">{fact.context}</p></div>)}</div></details></section>
    <footer className="border-t border-line pt-4 text-xs leading-6 text-muted"><p className="font-semibold uppercase tracking-wider">Data sources</p><p>Gold: Alpha Vantage · Macro: Federal Reserve Bank of St. Louis / FRED · Positioning: CFTC</p>{snapshot.economicCalendar && <FinanceCalendarAttribution />}<p>AI interpretation: OpenAI — {report.model} · Prompt {report.promptVersion}</p><p>Snapshot assembled: {snapshot.analysisDate} · Stored timestamps use UTC. Trading week: Monday–Friday UTC.</p></footer>
  </div>;
}
function Lines({ items }: { items: string[] }) { return <ul className="mt-3 space-y-2">{items.map((item, index) => <li key={index} className="flex gap-2 text-sm leading-6 text-secondary"><span aria-hidden="true" className="text-muted">·</span><span>{item}</span></li>)}</ul>; }
