"use client";
import { useState } from "react";
import { displayFacts } from "@/lib/ai/display-facts";
import type { GoldWeeklyAnalysis } from "@/lib/ai/schemas";
import type { GoldAnalysisSnapshot } from "@/lib/market-data/types";
import { paginate } from "@/lib/pagination";
import { Pagination } from "@/components/ui/pagination";
const title = "text-[11px] font-semibold uppercase tracking-[.14em] text-muted";
export function MacroScorecard({ snapshot, rows }: { snapshot: GoldAnalysisSnapshot; rows: GoldWeeklyAnalysis["macroScorecard"] }) {
  const [page, setPage] = useState(1);
  const facts = displayFacts(snapshot);
  const pageInfo = paginate(rows.length, page);
  const visibleRows = rows.slice(pageInfo.offset, pageInfo.end);
  return (
    <section className="overflow-hidden rounded-[10px] border border-line bg-surface"><div className="px-5 py-4"><h2 className={title}>Macro scorecard</h2><p className="mt-2 text-xs text-muted">Values and changes: provider facts and backend calculations. Gold impact and reasoning: AI interpretation.</p></div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[800px] text-left text-xs"><thead className="text-muted"><tr>{["Factor / source", "Current", "Change", "Gold impact", "Interpretation"].map(item => <th key={item} className="px-5 py-3 font-medium">{item}</th>)}</tr></thead><tbody>{visibleRows.map(row => { const fact = facts.find(item => item.key === row.indicatorKey); if (!fact) return null; return <tr key={row.indicatorKey} className="border-t border-line align-top"><td className="max-w-52 px-5 py-4"><a href={fact.sourceUrl} target="_blank" rel="noopener noreferrer" className="focus-ring font-medium text-foreground hover:text-accent">{fact.name}</a><p className="mt-2 text-muted">{fact.source} · {fact.date ?? "Date unavailable"}{fact.stale ? " · Stale" : ""}</p><p className="mt-1 text-muted">Fetched {new Date(fact.fetchedAt).toLocaleString("en-US", { timeZone: "UTC" })} UTC</p>{fact.releaseDate && <p className="mt-1 text-muted">Release {fact.releaseDate}</p>}</td><td className="px-5 py-4 tabular-nums text-secondary">{fact.value}</td><td className="px-5 py-4 tabular-nums text-secondary">{fact.change}</td><td className="px-5 py-4 capitalize text-secondary">{row.goldImpact}<p className="mt-1 text-[10px] text-muted">{row.importance} importance</p></td><td className="max-w-md px-5 py-4 leading-6 text-secondary">{row.explanation}<details className="mt-2 text-muted"><summary className="cursor-pointer">Calculation context</summary><p className="mt-2">{fact.context}</p></details></td></tr>; })}</tbody></table></div><div className="divide-y divide-line md:hidden">{visibleRows.map(row => { const fact = facts.find(item => item.key === row.indicatorKey); if (!fact) return null; return <article key={row.indicatorKey} className="space-y-2 p-5 text-sm"><div className="flex justify-between gap-4"><a href={fact.sourceUrl} target="_blank" rel="noopener noreferrer" className="font-medium text-foreground">{fact.name}</a><span className="text-xs capitalize text-accent">{row.goldImpact}</span></div><p className="text-secondary">{fact.value}</p><p className="text-xs text-muted">{fact.change} · {fact.source} · {fact.date ?? "Date unavailable"}{fact.stale ? " · Stale" : ""}</p><p className="text-xs leading-6 text-secondary">{row.explanation}</p><details className="text-xs text-muted"><summary>Source details</summary><p className="mt-2 leading-5">{fact.context}</p><p className="mt-2">Fetched {fact.fetchedAt}</p>{fact.releaseDate && <p>Release {fact.releaseDate}</p>}</details></article>; })}</div><Pagination currentPage={pageInfo.page} totalItems={rows.length} pageSize={10} onPageChange={setPage} itemLabel="macro factors" /></section>
  );
}
