"use client";
import { useEffect, useState } from "react";
import { Pencil, Plus, Save, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import type { ApiResponse } from "@/types/trade";

type Setup = { id: string; name: string; rules: string[]; avoidRules: string[] };
export function SetupManager() {
  const [items, setItems] = useState<Setup[]>([]); const [name, setName] = useState(""); const [rules, setRules] = useState<string[]>([""]); const [avoidRules, setAvoidRules] = useState<string[]>([""]); const [editing, setEditing] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  async function load() { setLoading(true); try { const response = await fetch("/api/setup-types"); const json: ApiResponse<Setup[]> = await response.json(); if (!response.ok || !json.success) throw new Error(json.success ? "Unable to load setup types" : json.error); setItems(json.data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load setup types"); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  function reset() { setName(""); setRules([""]); setAvoidRules([""]); setEditing(null); setError(""); }
  async function save() { if (!name.trim() || pending) return; setPending(true); setError(""); try { const response = await fetch(editing ? `/api/setup-types/${editing}` : "/api/setup-types", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, rules: rules.map(rule => rule.trim()).filter(Boolean), avoidRules: avoidRules.map(rule => rule.trim()).filter(Boolean) }) }); const json: ApiResponse<Setup> = await response.json(); if (!response.ok || !json.success) throw new Error(json.success ? "Unable to save setup type" : json.error); reset(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save setup type"); } finally { setPending(false); } }
  async function remove(id: string) { if (!window.confirm("Delete this setup type?")) return; setPending(true); setError(""); try { const response = await fetch(`/api/setup-types/${id}`, { method: "DELETE" }); const json: ApiResponse<{ id: string }> = await response.json(); if (!response.ok || !json.success) throw new Error(json.success ? "Unable to delete setup type" : json.error); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete setup type"); } finally { setPending(false); } }
  return <div className="space-y-5"><div className="rounded-[9px] border border-line bg-surface p-5"><div className="flex flex-col gap-3"><input value={name} onChange={event => setName(event.target.value)} className="form-input" placeholder="Setup name" maxLength={80} /><RuleEditor title="Take-trade rules" values={rules} setValues={setRules} placeholder="Liquidity sweep is confirmed" /><RuleEditor title="Do not take the trade if…" values={avoidRules} setValues={setAvoidRules} placeholder="Price is already extended" /><div className="flex gap-2"><Button variant="primary" onClick={save} disabled={pending || !name.trim()}>{pending ? <Spinner label="Saving setup" /> : editing ? <Save size={16} /> : <Plus size={16} />}{editing ? "Update setup" : "Add setup"}</Button>{editing && <Button variant="ghost" onClick={reset} disabled={pending}><X size={16} />Cancel</Button>}</div></div>{error && <p role="alert" className="mt-3 text-sm text-loss">{error}</p>}</div><div className="overflow-hidden rounded-[9px] border border-line bg-surface">{loading ? <div className="flex items-center gap-2 p-5 text-sm text-muted"><Spinner label="Loading setup types" />Loading setup types…</div> : items.map(item => <div key={item.id} className="border-b border-line/70 px-5 py-3 last:border-0"><div className="flex items-center justify-between"><span className="text-sm font-medium text-setup">{item.name}</span><div className="flex gap-1"><Button className="h-8 px-2" onClick={() => { setEditing(item.id); setName(item.name); setRules(item.rules.length ? item.rules : [""]); setAvoidRules(item.avoidRules.length ? item.avoidRules : [""]); }} disabled={pending}><Pencil size={14} /><span className="sr-only">Edit {item.name}</span></Button><Button variant="danger" className="h-8 px-2" onClick={() => remove(item.id)} disabled={pending}><Trash2 size={14} /><span className="sr-only">Delete {item.name}</span></Button></div></div>{item.rules.length > 0 && <ul className="mt-2 list-disc pl-5 text-xs text-muted">{item.rules.map(rule => <li key={rule}>{rule}</li>)}</ul>}{item.avoidRules.length > 0 && <ul className="mt-2 list-disc pl-5 text-xs text-loss">{item.avoidRules.map(rule => <li key={rule}>{rule}</li>)}</ul>}</div>)}</div></div>;
}

function RuleEditor({ title, values, setValues, placeholder }: { title: string; values: string[]; setValues: React.Dispatch<React.SetStateAction<string[]>>; placeholder: string }) { return <div className="space-y-2"><p className="text-sm font-medium text-secondary">{title}</p>{values.map((rule, index) => <div key={index} className="flex gap-2"><input value={rule} onChange={event => setValues(current => current.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} className="form-input flex-1" placeholder={`${placeholder} (${index + 1})`} maxLength={200} /><Button type="button" variant="ghost" className="h-10 px-2" onClick={() => setValues(current => current.length > 1 ? current.filter((_, itemIndex) => itemIndex !== index) : current)}><X size={15} /></Button></div>)}<Button type="button" variant="ghost" onClick={() => setValues(current => [...current, ""])}><Plus size={15} />Add rule</Button></div>; }
